### ISSUE TITLE
Layout on mobile hides parts

### ISSUE THREAD

**Issue by ChristianTacke** [marudor/bahn.expert#711] opened 2022-12-17 19:51 UTC
**Describe the bug**

On my mobile with Firefox I can't scroll up enough to see the station name of the first station of that train. I hope the screenshot is clear enough.

if there's a trick to scroll further up, then that is not obvious enough to me.

**To Reproduce**
1. Go to https://bahn.expert/details/ICE%2029/2022-12-07
2. Try to scroll up.

**Expected behavior**
Being able to see the top entry fully.

**Screenshots**
![t-1](https://user-images.githubusercontent.com/8560110/208263609-9d9d26cf-5789-4f90-8416-c08de5f00c9d.jpg)

**Desktop (please complete the following information):**
works as expected

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A1
 - OS: LineageOS latest (Android 12)
 - Browser Firefox
 - Version latest, 108.1.0

**Comment by marudor** [comment] 2022-12-24 22:14
Most likely it has to do with a very small viewport (Small device in your case?)
I can't reproduce it in any way.
I'm closing this as this is most likely still a bug, but there is nothing I can do.

**Closed by marudor** 2022-12-24 22:14 UTC
Labels: bug

**Comment by ChristianTacke** [comment] 2022-12-25 09:30
Yes, effectively a small viewport.

I am definitely not an expert on CSS, but can't the CSS be changed so that one scroll the lower (main) part independantly of the height of the top bar?
