### ISSUE TITLE
Ability to choose default home page

### ISSUE THREAD

**Issue by leoheitmannruiz** [marudor/bahn.expert#985] opened 2024-11-23 14:09 UTC
**Is your feature request related to a problem? Please describe.**

I use bahn.expert as a PWA and have so far only used the routing functionality.

Every time I open the PWA, I click the hamburger menu and then routing. I'd like to not have to do this and instead be able to choose to be shown (in my case) the routing page directly, when I open the PWA.

Is this already possible?

**Describe the solution you'd like**

Not sure, but perhaps an option in the settings to choose the default home page.

**Additional context**

Thanks a lot!

**Comment by Ein-Tim** [comment] 2024-11-23 18:59
- This seems like a duplicate of #957

**Closed as completed** 2024-11-23 22:34 UTC
Labels: feature
